
[house_specific]

	[house_specific.opancakes]
		jail_game = true

[modules]

	[modules."data_&_analytics"]
		"&7improved_stats:_copy_json" = true
		"&7improved_stats:_categories" = true
		"&7improved_stats:_alphabetical" = true
		house_tracker = false
		"&7house_tracker:_entry_delay" = 300
		improved_stats = true

	[modules.pro_tools]
		"//redo" = true
		"&7cooldown_ping:_essential_notifications" = false
		"&7cooldown_ping:_quiet_mode" = false
		cooldown_ping = true

	[modules.chat]
		"&7hide_spam:_join_messages" = false
		"&7hide_spam:_death_messages" = false
		hide_spam = false
		hide_asterisk = true

	[modules.commands]
		"/rejoin" = true
		"/palette" = false

